server {
    listen 9000;
    server_name _;

    root /var/www;
    autoindex on;

    location /download {
        alias /var/www/download;
        autoindex on;
        add_header Content-Disposition "attachment";
    }

    location /health {
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}
